export default [
    ['🎸 🔁 🎄', 'Rocking Around the Christmas Tree'],
    ['👁️ 🏠 🎄', "I'll Be Home For Christmas"],
    ['❄️ ☃️', 'Frosty the Snowman'],
    ['🎅🏻🛷 🏘️🏦🏡⛪🏠🏢🏥🏨', 'Santa Claus is Coming to Town'],
    ['👁️ 👀 👩🏻 💋 🎅🏻', 'I Saw Mommy Kissing Santa Claus'],
    ['🙊 🌃', 'Silent Night'],
    ['🦌 🔴👃', 'Rudolph the Red-Nosed Reindeer'],
    ['👵🏻 🚗 🦌', 'Grandma Got Run Over by a Reindeer'],
    ['🥈 🔔🔔', 'Silver Bells'],
    ['📆📆📆📆📆📆📆📆📆📆📆📆 🎄', 'The 12 Days of Christmas'],
    ['🌰🌰 🍳 🔥', 'Chestnuts Roasting on an Open Fire'],
    ['😴💭 ❄️ 🎄', "I'm Dreaming of a White Christmas"],
    ['🎶 🛎️ 🎸', 'Jingle Bell Rock'],
    ['🎉 ➡️ 🌎', 'Joy to the World'],
    ['🙏🏻❄️ 🙏🏻❄️ 🙏🏻❄️', 'Let It Snow! Let It Snow! Let It Snow!'],
    ['🎅🏻 👶🏻', 'Santa Baby'],
    ['🥁 👦🏻', 'Drummer Boy'],
    ['👶🏻 🌬️❄️ 🏞️', "Baby It's Cold Outside"],
    ['👩🏻💭 🎁🎄 ☝️', 'All I Want for Christmas is You'],
    ['🤴 🤴 🤴', 'We Three Kings'],
    ['👧🏻💭 🎁🎄 ✌️😬', 'All I Want for Christmas is My Two Front Teeth'],
    ['🗓️ ⏪ 🎄', 'Last Christmas'],
    ['🕎 🎶', 'The Hanukkah Song'],
];
